<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DVG7SGTJ" failures="0" tests="10" name="Practicing_TestNG.Groupings" time="0.020" errors="1" timestamp="2025-08-03T11:59:53 IST" skipped="0">
  <testcase classname="Practicing_TestNG.Groupings" name="failingDependentMethod" time="0.001"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="group2" time="0.001"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="group1" time="0.002"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="dummyMethod" time="0.010">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Practicing_TestNG.Groupings.dummyMethod(Groupings.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- dummyMethod -->
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="group3" time="0.001"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="group4" time="0.000"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="dummyMethod2" time="0.001"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="passingDependentMethod" time="0.002"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="passingGroup" time="0.001"/>
  <system-out/>
  <testcase classname="Practicing_TestNG.Groupings" name="passingDependentGroup" time="0.001"/>
  <system-out/>
</testsuite> <!-- Practicing_TestNG.Groupings -->
